apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::211125410910:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-o5VsEExr9wIu
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::211125410910:user/ReddyN  
      username: ReddyN 
kind: ConfigMap
metadata:
  creationTimestamp: "2025-02-27T19:50:35Z"
  name: aws-auth
  namespace: kube-system
  uid: 480c2aaf-f2f7-4650-9ccc-1e5688b8917e





  